logging.file.name=application.log
name="adam"

spring.liquibase.enabled=false

# Stratégie indispensable pour le Reverse Proxy (Caddy)
server.forward-headers-strategy=framework

# Database connection settings
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/si-legale?serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:adam}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Liquibase configuration
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml

# Configuration Keycloak (OIDC) - Liée aux variables du docker-compose
spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER_URI}
spring.security.oauth2.client.provider.keycloak.issuer-uri=${KEYCLOAK_ISSUER_URI}
spring.security.oauth2.client.registration.keycloak.client-id=avo-test-client

# Yente Configuration
yente.api.url=${YENTE_API_URL:http://localhost:8000}
yente.api.default.dataset=tous_les_datasets?expand=true
yente.api.default.match.path=/match/
yente.api.key=adam
aml.block.threshold=0.60
aml.suspect.threshold=0.50
aml.match.batch.size=100