server.port=8080

name= "adam"
spring.devtools.restart.additional-paths=file:d:/avo-maitrise/front/src
spring.web.resources.static-locations=classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:d:/avo-maitrise/front/dist/front/browser/

# server.servlet.context-path=/api