# ===================================================================
# BASE CONFIGURATION (Shared across all profiles)
# ===================================================================

# --- Spring Profile ---
spring.profiles.active=staging

# --- Static Resources & DevTools ---
spring.devtools.restart.additional-paths=file:d:/avo-maitrise/front/src
spring.web.resources.static-locations=classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:d:/avo-maitrise/front/dist/front/browser/

# --- Database & JPA Defaults ---
spring.datasource.url=jdbc:mysql://localhost:3306/si-legale?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=adam
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# --- Liquibase ---
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

# --- Security & Keycloak Defaults ---
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:7070/realms/avo-app-test
spring.security.oauth2.client.registration.keycloak.client-id=avo-test-client

keycloak.auth-server-url=http://localhost:7070
keycloak.realm=avo-app-test
keycloak.admin-client-id=avo-admin-client
keycloak.admin-client-secret=WOj6uy5Q5EMI3rO6WWZFERgukq9mz6pm

# --- Yente API Defaults ---
yente.api.url=http://localhost:8000
yente.api.default.dataset=tous_les_datasets?expand=true
yente.api.default.match.path=/match/
yente.api.key=adam
aml.block.threshold=0.60
aml.suspect.threshold=0.50
aml.match.batch.size=100


# --- Logging Defaults ---
logging.file.name=avo-application.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n



# Configuration SMTP Brevo
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=b00140001@smtp-brevo.com

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.from= adamlaftimi@gmail.com

# Optionnel : Définir des timeouts pour éviter les blocages
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=3000
spring.mail.properties.mail.smtp.writetimeout=5000

# Actuator & HAL Explorer
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
