package com.avo.entities;

public enum ClientStatus {
    AML_REQUIRED,
    VERIFICATION_AML_REQUIRED,
    AML_VALIDATED,
    INDULGENCE_REQUIRED,
    INDULGENCE_VALIDATED,
    VALIDATED,
    BLOCKED,
    SUSPICIOUS
}
