const fs = require('fs');

const BORD_TRANSLATIONS = {
  en: {
    "GREETING": "Hello, {{ username }}",
    "WELCOME_TEXT": "Welcome to your SI-LEGALE dashboard.",
    "ONLINE_MASTER": "Online Master",
    "NEW_CLIENT": "New Client",
    "NEW_DOSSIER": "New Case",
    "AGENDA": "Agenda",
    "ALERTS_URGENT": "{{count}} Urgent Alerts",
    "IGNORE": "Ignore",
    "ANALYZE_CLIENT": "Analyze Client",
    "AML_STATUS_TITLE": "AML Compliance Status Green",
    "AML_STATUS_TEXT": "No alerts requiring immediate attention.",
    "ACTIVE_DOSSIERS": "Active Cases",
    "RISKS_ALERTS": "Alerts & Risks",
    "MY_AGENDA": "My Agenda",
    "ACTIVE_CLIENTS": "Active Clients",
    "AGENDA_TITLE": "Agenda & Deadlines",
    "SEE_ALL": "See All",
    "OFFICE": "Office",
    "NO_APPOINTMENTS": "No appointments today",
    "IMPORTANT_TASKS": "Important Tasks",
    "REMAINING": "remaining",
    "MARK_DONE": "Mark Done",
    "DUE_DATE": "Due Date",
    "PRIORITY": "Priority",
    "ALL_TASKS_DONE": "All tasks are completed",
    "RECENT_DOSSIERS": "Recent Cases",
    "REF": "Ref",
    "GENERAL_LAW": "General Law",
    "NO_DOSSIERS": "No recent cases",
    "CREATE_FIRST_DOSSIER": "Create your first case",
    "DELETE": "Delete"
  },
  es: {
    "GREETING": "Hola, {{ username }}",
    "WELCOME_TEXT": "Bienvenido a su panel de SI-LEGALE.",
    "ONLINE_MASTER": "Maestro en Línea",
    "NEW_CLIENT": "Nuevo Cliente",
    "NEW_DOSSIER": "Nuevo Expediente",
    "AGENDA": "Agenda",
    "ALERTS_URGENT": "{{count}} Alertas Urgentes",
    "IGNORE": "Ignorar",
    "ANALYZE_CLIENT": "Analizar Cliente",
    "AML_STATUS_TITLE": "Estado de cumplimiento AML en verde",
    "AML_STATUS_TEXT": "No hay alertas que requieran atención inmediata.",
    "ACTIVE_DOSSIERS": "Expedientes Activos",
    "RISKS_ALERTS": "Alertas y Riesgos",
    "MY_AGENDA": "Mi Agenda",
    "ACTIVE_CLIENTS": "Clientes Activos",
    "AGENDA_TITLE": "Agenda y Plazos",
    "SEE_ALL": "Ver Todo",
    "OFFICE": "Oficina",
    "NO_APPOINTMENTS": "No hay citas hoy",
    "IMPORTANT_TASKS": "Tareas Importantes",
    "REMAINING": "restantes",
    "MARK_DONE": "Marcar como Hecho",
    "DUE_DATE": "Fecha de Vencimiento",
    "PRIORITY": "Prioridad",
    "ALL_TASKS_DONE": "Todas las tareas están completadas",
    "RECENT_DOSSIERS": "Expedientes Recientes",
    "REF": "Ref",
    "GENERAL_LAW": "Derecho General",
    "NO_DOSSIERS": "No hay expedientes recientes",
    "CREATE_FIRST_DOSSIER": "Cree su primer expediente",
    "DELETE": "Eliminar"
  },
  de: {
    "GREETING": "Hallo, {{ username }}",
    "WELCOME_TEXT": "Willkommen bei Ihrem SI-LEGALE Dashboard.",
    "ONLINE_MASTER": "Online Meister",
    "NEW_CLIENT": "Neuer Kunde",
    "NEW_DOSSIER": "Neues Dossier",
    "AGENDA": "Agenda",
    "ALERTS_URGENT": "{{count}} Dringende Warnungen",
    "IGNORE": "Ignorieren",
    "ANALYZE_CLIENT": "Kunde Analysieren",
    "AML_STATUS_TITLE": "AML-Compliance-Status Grün",
    "AML_STATUS_TEXT": "Keine Warnungen erfordern sofortige Aufmerksamkeit.",
    "ACTIVE_DOSSIERS": "Aktive Dossiers",
    "RISKS_ALERTS": "Warnungen & Risiken",
    "MY_AGENDA": "Meine Agenda",
    "ACTIVE_CLIENTS": "Aktive Kunden",
    "AGENDA_TITLE": "Agenda & Fristen",
    "SEE_ALL": "Alle Anzeigen",
    "OFFICE": "Büro",
    "NO_APPOINTMENTS": "Keine Termine heute",
    "IMPORTANT_TASKS": "Wichtige Aufgaben",
    "REMAINING": "verbleibend",
    "MARK_DONE": "Als erledigt markieren",
    "DUE_DATE": "Fälligkeitsdatum",
    "PRIORITY": "Priorität",
    "ALL_TASKS_DONE": "Alle Aufgaben sind erledigt",
    "RECENT_DOSSIERS": "Letzte Dossiers",
    "REF": "Ref",
    "GENERAL_LAW": "Allgemeines Recht",
    "NO_DOSSIERS": "Keine aktuellen Dossiers",
    "CREATE_FIRST_DOSSIER": "Erstellen Sie Ihr erstes Dossier",
    "DELETE": "Löschen"
  },
  it: {
    "GREETING": "Ciao, {{ username }}",
    "WELCOME_TEXT": "Benvenuto nella tua dashboard SI-LEGALE.",
    "ONLINE_MASTER": "Maestro Online",
    "NEW_CLIENT": "Nuovo Cliente",
    "NEW_DOSSIER": "Nuovo Fascicolo",
    "AGENDA": "Agenda",
    "ALERTS_URGENT": "{{count}} Avvisi Urgenti",
    "IGNORE": "Ignorare",
    "ANALYZE_CLIENT": "Analizza Cliente",
    "AML_STATUS_TITLE": "Stato di conformità AML verde",
    "AML_STATUS_TEXT": "Nessun avviso che richiede attenzione immediata.",
    "ACTIVE_DOSSIERS": "Fascicoli Attivi",
    "RISKS_ALERTS": "Avvisi e Rischi",
    "MY_AGENDA": "La mia Agenda",
    "ACTIVE_CLIENTS": "Clienti Attivi",
    "AGENDA_TITLE": "Agenda e Scadenze",
    "SEE_ALL": "Vedi Tutto",
    "OFFICE": "Ufficio",
    "NO_APPOINTMENTS": "Nessun appuntamento oggi",
    "IMPORTANT_TASKS": "Compiti Importanti",
    "REMAINING": "rimanenti",
    "MARK_DONE": "Segna come Fatto",
    "DUE_DATE": "Scadenza",
    "PRIORITY": "Priorità",
    "ALL_TASKS_DONE": "Tutti i compiti sono stati completati",
    "RECENT_DOSSIERS": "Fascicoli Recenti",
    "REF": "Rif",
    "GENERAL_LAW": "Diritto Generale",
    "NO_DOSSIERS": "Nessun fascicolo recente",
    "CREATE_FIRST_DOSSIER": "Crea il tuo primo fascicolo",
    "DELETE": "Elimina"
  }
};

const basePath = 'd:/avo-maitrise/front/public/assets/i18n';

for (const [lang, translations] of Object.entries(BORD_TRANSLATIONS)) {
  const filePath = `${basePath}/${lang}.json`;
  if (fs.existsSync(filePath)) {
    const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));
    data['BORD'] = translations;
    fs.writeFileSync(filePath, JSON.stringify(data, null, 2));
    console.log(`Updated ${lang}.json`);
  }
}
