const fs = require('fs');

const arTranslations = {
  "LANGUAGE": {
    "FR": "Français",
    "EN": "English",
    "ES": "Español",
    "DE": "Deutsch",
    "IT": "Italiano",
    "AR": "العربية"
  },
  "MENU": {
    "HOME": "الرئيسية",
    "AML": "الامتثال (AML)",
    "DILIGENCE_TRACKING": "تتبع العناية الواجبة",
    "CALENDAR": "التقويم القضائي",
    "DOSSIER": "إدارة القضايا",
    "CLIENTS": "إدارة العملاء",
    "MODEL": "إدارة الوثائق (GED)",
    "BILLING": "الفواتير",
    "BILLING_DASHBOARD": "لوحة معلومات الفواتير",
    "ADMINISTRATION": "الإدارة",
    "LOGOUT": "تسجيل الخروج"
  },
  "BORD": {
    "GREETING": "مرحباً، {{ username }}",
    "WELCOME_TEXT": "مرحباً بك في لوحة معلومات SI-LEGALE الخاصة بك.",
    "ONLINE_MASTER": "الأستاذ متصل",
    "NEW_CLIENT": "عميل جديد",
    "NEW_DOSSIER": "قضية جديدة",
    "AGENDA": "جدول الأعمال",
    "ALERTS_URGENT": "{{count}} تنبيهات عاجلة",
    "IGNORE": "تجاهل",
    "ANALYZE_CLIENT": "تحليل العميل",
    "AML_STATUS_TITLE": "حالة امتثال مكافحة غسل الأموال خضراء",
    "AML_STATUS_TEXT": "لا توجد تنبيهات تتطلب اهتماماً فورياً.",
    "ACTIVE_DOSSIERS": "القضايا النشطة",
    "RISKS_ALERTS": "التنبيهات والمخاطر",
    "MY_AGENDA": "جدول أعمالي",
    "ACTIVE_CLIENTS": "العملاء النشطون",
    "AGENDA_TITLE": "الجدول الزمني والمواعيد النهائية",
    "SEE_ALL": "عرض الكل",
    "OFFICE": "المكتب",
    "NO_APPOINTMENTS": "لا توجد مواعيد اليوم",
    "IMPORTANT_TASKS": "المهام الهامة",
    "REMAINING": "متبقية",
    "MARK_DONE": "تحديد كمنجز",
    "DUE_DATE": "تاريخ الاستحقاق",
    "PRIORITY": "الأولوية",
    "ALL_TASKS_DONE": "تم إنجاز جميع المهام",
    "RECENT_DOSSIERS": "القضايا الأخيرة",
    "REF": "المرجع",
    "GENERAL_LAW": "القانون العام",
    "NO_DOSSIERS": "لا توجد قضايا حديثة",
    "CREATE_FIRST_DOSSIER": "إنشاء أول قضية لك",
    "DELETE": "حذف"
  },
  "CALENDAR": {
    "TITLE": "التقويم القضائي",
    "DAY_VIEW": "عرض اليوم",
    "WEEK_VIEW": "عرض الأسبوع",
    "AGENDA_DAY": "جدول أعمال اليوم",
    "AGENDA_WEEK": "اجتماعات الأسبوع",
    "ADD_MEETING": "إضافة اجتماع",
    "TODAY": "اليوم",
    "CURRENT_WEEK": "الأسبوع الحالي",
    "HOURS": "الساعات",
    "TIME": "الوقت :",
    "DELETE": "حذف",
    "NO_HEARINGS_TODAY": "لا توجد جلسات استماع مقررة لهذا اليوم.",
    "NO_HEARINGS": "لا توجد جلسات استماع.",
    "STATUS_LEGEND": "دليل الحالة:",
    "URGENT": "عاجل",
    "STANDARD": "عادي",
    "POSTPONED": "مؤجل"
  },
  "MODEL": {
    "TITLE": "قائمة النماذج والموارد الداخلية",
    "SUBTITLE": "البحث، تصفية وإدارة نماذج الوثائق والسياسات الداخلية لشركتك.",
    "SEARCH_FILTERS": "خيارات البحث والتصفية",
    "SEARCH_PLACEHOLDER": "ابحث بالاسم، الوصف...",
    "ALL_CATEGORIES": "جميع الفئات",
    "CONTRACTS": "عقود",
    "KYC_FORMS": "نماذج اعرف عميلك",
    "POLICIES": "سياسات",
    "INTERNAL_DOCS": "وثائق داخلية",
    "ALL_STATUSES": "جميع الحالات",
    "ACTIVE": "نشط",
    "IN_REVIEW": "قيد المراجعة",
    "ARCHIVED": "مؤرشف / قديم",
    "DOCUMENTS_FOUND": "نموذج(نماذج) وثيقة تم العثور عليها.",
    "ADD_NEW": "إضافة نموذج جديد",
    "NO_MODELS": "لا يوجد نموذج وثيقة",
    "NO_MODELS_DESC": "لا يتطابق أي نموذج وثيقة مع فلاتر البحث الحالية.",
    "UPDATED": "محدث",
    "RECENT": "حديث",
    "NO_DESC": "لم يتم تقديم وصف.",
    "CATEGORY": "فئة",
    "FILE": "ملف",
    "DOWNLOAD": "تحميل",
    "EDIT": "تعديل",
    "DELETE": "حذف",
    "CREATE_MODAL_TITLE": "إنشاء نموذج جديد",
    "CREATE_MODAL_DESC": "املأ المعلومات أدناه لإضافة نموذج وثيقة جديد.",
    "FORM_TITLE": "عنوان النموذج",
    "FORM_DESC": "الوصف / تعليمات الاستخدام",
    "FORM_FILE": "ملف النموذج",
    "FORM_FILE_HELP": "PDF, DOCX أو XLSX فقط.",
    "BTN_CANCEL": "إلغاء",
    "BTN_CREATE": "إنشاء نموذج"
  },
  "CRM": {
    "BREADCRUMB_DASHBOARD": "لوحة المعلومات",
    "BREADCRUMB_CLIENTS": "إدارة العملاء",
    "DIRECTORY": "الدليل",
    "CLIENTS_CONTACTS": "العملاء وجهات الاتصال",
    "SUBTITLE": "إدارة قاعدة بيانات عملائك مع مراقبة غسل الأموال في الوقت الفعلي وتتبع صارم للامتثال اعرف عميلك.",
    "ALERTS_CRITICAL": "تنبيهات غسل أموال حرجة",
    "NO_ALERTS": "لا توجد تنبيهات",
    "NEW_CLIENT": "عميل جديد",
    "TAB_ALL": "جميع العملاء",
    "TAB_PERSONNE": "الأشخاص الطبيعيون",
    "TAB_SOCIETE": "الشركات",
    "TAB_ASSOCIATION": "الجمعيات",
    "TAB_INSTITUTION": "المؤسسات",
    "SEARCH_PLACEHOLDER": "ابحث بالاسم، المعرف، أو البلد...",
    "FILTER_ALL_TYPES": "جميع الأنواع",
    "FILTER_PERSON": "شخص طبيعي",
    "FILTER_COMPANY": "شركة / كيان",
    "FILTER_ASSOCIATION": "جمعية",
    "FILTER_INSTITUTION": "مؤسسة",
    "FILTER_ALL_RISKS": "مخاطر غسل الأموال (الكل)",
    "RISK_HIGH": "مخاطر عالية",
    "RISK_MEDIUM": "مخاطر متوسطة",
    "RISK_LOW": "مخاطر منخفضة",
    "LOADING": "جاري تحميل دليل العملاء...",
    "NO_CLIENT_FOUND": "لم يتم العثور على عميل",
    "NO_CLIENT_DESC": "ابدأ بإضافة أول عميل لك إلى الدليل.",
    "CREATE_CLIENT": "إنشاء عميل",
    "SHOWING": "عرض",
    "TO": "إلى",
    "OUT_OF": "من أصل",
    "MATTERS_LC": "قضايا"
  },
  "AML_COMPLIANCE": {
    "BREADCRUMB_DASHBOARD": "لوحة المعلومات",
    "BREADCRUMB_AML": "الامتثال (AML)",
    "TITLE_PREFIX": "تتبع ال",
    "TITLE_HIGHLIGHT": "الامتثال (AML / KYC)",
    "SUBTITLE": "تحليل الوضع العام للامتثال الخاص بشركتك، وعرض مستوى المخاطر، والإشراف على فحص العقوبات.",
    "BTN_TRIGGER_CLIENTS": "فحص العملاء",
    "BTN_REPORT_CLIENTS": "تقرير العملاء (PDF)",
    "BTN_REPORT_UBOS": "تقرير المستفيدين (PDF)",
    "LOADING_TEXT": "جاري تحميل مؤشرات الامتثال...",
    "KPI_COMPLIANCE_RATE": "معدل الامتثال",
    "KPI_COMPLIANCE_DESC": "من العملاء الصالحين",
    "KPI_ALERTS": "تنبيهات العقوبات",
    "KPI_ALERTS_PENDING": "مطابقات معلقة",
    "KPI_ALERTS_REQ": "مطلوب تحليل فوري للعقوبات.",
    "KPI_ALERTS_NO_HIT": "لا يوجد تطابق حرج.",
    "KPI_PENDING_REVIEW": "ملفات قيد المراجعة",
    "KPI_PENDING_DESC": "في انتظار الموافقة",
    "KPI_PENDING_FORMS": "نماذج للملء",
    "KPI_AVG_RISK": "متوسط درجة المخاطرة",
    "KPI_AVG_RISK_DESC": "متوسط درجة الفحص",
    "CHART_SECTOR_TITLE": "أهم القطاعات المعرضة",
    "CHART_SECTOR_DESC": "متوسط درجة فحص العقوبات حسب القطاع",
    "VOL": "الحجم: ",
    "AVG_SCORE": " - متوسط الدرجة: ",
    "NO_SECTORS": "لا توجد قطاعات مسجلة.",
    "CHART_TYPE_TITLE": "التوزيع حسب الفئة",
    "CHART_TYPE_DESC": "نسبة العملاء المسجلين حسب نوع الكيان",
    "NO_TYPES": "لا توجد أنواع عملاء مسجلة.",
    "TABLE_TITLE": "لوحة معلومات العملاء",
    "TABLE_DESC": "فحص الحالة الفردية لكل عميل واتخاذ قرارات الامتثال",
    "SEARCH_PLACEHOLDER": "البحث عن عميل...",
    "FILTER_ALL_TYPES": "جميع الأنواع",
    "FILTER_TYPE_PERSON": "شخص طبيعي",
    "FILTER_TYPE_COMPANY": "شركة / كيان",
    "FILTER_TYPE_ASSOCIATION": "جمعية",
    "FILTER_TYPE_INSTITUTION": "مؤسسة",
    "FILTER_ALL_STATUS": "جميع الحالات",
    "FILTER_ALL_RISKS": "جميع المخاطر",
    "FILTER_RISK_HIGH": "مخاطر عالية (>=70%)",
    "FILTER_RISK_MEDIUM": "مخاطر متوسطة (40-69%)",
    "FILTER_RISK_LOW": "مخاطر منخفضة (<40%)",
    "TH_CLIENT": "العميل",
    "TH_TYPE_SECTOR": "النوع والقطاع",
    "TH_MATCHES": "مطابقات العقوبات",
    "TH_STATUS": "حالة الامتثال",
    "TH_ACTIONS": "الإجراءات",
    "UNKNOWN_COUNTRY": "دولة غير معروفة",
    "NO_SECTOR": "بدون قطاع",
    "HITS": "تطابق(ات)",
    "MAX_SCORE": "الدرجة القصوى: ",
    "TOOLTIP_CLIENT_SHEET": "ملف العميل",
    "TOOLTIP_KYC_DOSSIER": "ملف العناية الواجبة KYC",
    "TOOLTIP_DOWNLOAD_PDF": "تحميل ملف المراقبة (PDF)",
    "NO_CLIENTS_FOUND": "لا يوجد عميل يطابق معايير التصفية.",
    "PAGINATION_SHOWING": "عرض",
    "PAGINATION_FROM": "(من ",
    "PAGINATION_TO": " إلى ",
    "PAGINATION_OUT_OF": " من أصل ",
    "PAGINATION_CLIENTS": " عملاء)",
    "MODAL_TITLE_UBO": "تقرير المراجعة (UBOs)",
    "MODAL_TITLE_CLIENT": "تقرير المراجعة (العملاء)",
    "MODAL_SUBTITLE": "الإنشاء عبر JasperReports",
    "MODAL_DESC_UBO": "حدد فترة التحليل للمستفيدين الفعليين.",
    "MODAL_DESC_CLIENT": "حدد فترة التحليل للعملاء.",
    "MODAL_START_DATE": "تاريخ البدء",
    "MODAL_END_DATE": "تاريخ الانتهاء",
    "MODAL_CANCEL": "إلغاء",
    "MODAL_GENERATING": "جاري الإنشاء...",
    "MODAL_DOWNLOAD": "تحميل PDF",
    "ALERTS": {
      "CONFIRM_TITLE": "تحديث الحالة؟",
      "CONFIRM_MSG": "هل أنت متأكد من تغيير الحالة إلى \"{{status}}\"؟",
      "UPDATE_SUCCESS": "تم تحديث الحالة بنجاح.",
      "UPDATE_ERROR": "تعذر تحديث الحالة."
    }
  }
};

const basePath = 'd:/avo-maitrise/front/public/assets/i18n';
const arFilePath = `${basePath}/ar.json`;

fs.writeFileSync(arFilePath, JSON.stringify(arTranslations, null, 2));
console.log('Created ar.json');

// Update LANGUAGE.AR in all files
const files = ['fr.json', 'en.json', 'es.json', 'de.json', 'it.json'];
for (const file of files) {
  const filePath = `${basePath}/${file}`;
  if (fs.existsSync(filePath)) {
    const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));
    if (!data.LANGUAGE) data.LANGUAGE = {};
    data.LANGUAGE.AR = "العربية";
    fs.writeFileSync(filePath, JSON.stringify(data, null, 2));
  }
}
console.log('Added LANGUAGE.AR to other files');
