const fs = require('fs');

const data = JSON.parse(fs.readFileSync('d:/avo-maitrise/front/public/assets/i18n/ar.json', 'utf8'));

data.AML_STATUS = {
  "AML_REQUIRED": "الامتثال مطلوب",
  "VERIFICATION_AML_REQUIRED": "التحقق من الامتثال",
  "AML_VALIDATED": "تم التحقق",
  "INDULGENCE_REQUIRED": "طلب إعفاء",
  "VALIDATED": "معتمد",
  "BLOCKED": "محظور"
};

data.AML_COMPLIANCE = {
  "BREADCRUMB_DASHBOARD": "لوحة القيادة",
  "BREADCRUMB_AML": "الامتثال AML",
  "TITLE_PREFIX": "تتبع ",
  "TITLE_HIGHLIGHT": "الامتثال (AML / KYC)",
  "SUBTITLE": "قم بتحليل وضع الامتثال العام لمكتبك، وعرض مستوى المخاطر حسب القطاع، والإشراف على فحص العقوبات.",
  "BTN_TRIGGER_CLIENTS": "بدء التحقق من العملاء",
  "BTN_REPORT_CLIENTS": "تقرير العملاء (PDF)",
  "BTN_REPORT_UBOS": "تقرير المستفيدين (PDF)",
  "LOADING_TEXT": "جاري تحميل مؤشرات الامتثال...",
  "KPI_COMPLIANCE_RATE": "معدل الامتثال",
  "KPI_COMPLIANCE_DESC": "من العملاء المعتمدين",
  "KPI_ALERTS": "تنبيهات العقوبات",
  "KPI_ALERTS_PENDING": "تطابقات معلقة",
  "KPI_ALERTS_REQ": "مطلوب مراجعة العقوبات فوراً.",
  "KPI_ALERTS_NO_HIT": "لا يوجد تطابقات حرجة معلقة.",
  "KPI_PENDING_REVIEW": "ملفات قيد المراجعة",
  "KPI_PENDING_DESC": "في انتظار الموافقة",
  "KPI_PENDING_FORMS": "نماذج يجب ملؤها",
  "KPI_AVG_RISK": "متوسط درجة الخطر",
  "KPI_AVG_RISK_DESC": "متوسط درجة الفحص",
  "CHART_SECTOR_TITLE": "أكثر قطاعات الأعمال تعرضاً",
  "CHART_SECTOR_DESC": "متوسط درجة فحص العقوبات حسب القطاع",
  "VOL": "حجم: ",
  "AVG_SCORE": " - متوسط الدرجة: ",
  "NO_SECTORS": "لا توجد قطاعات أعمال مدرجة.",
  "CHART_TYPE_TITLE": "التوزيع حسب الفئات",
  "CHART_TYPE_DESC": "نسبة العملاء المسجلين حسب نوع الكيان",
  "NO_TYPES": "لا توجد أنواع عملاء مسجلة.",
  "TABLE_TITLE": "لوحة معلومات العملاء",
  "TABLE_DESC": "افحص الحالة الفردية لكل عميل وطبق قرارات الامتثال",
  "SEARCH_PLACEHOLDER": "ابحث عن عميل...",
  "FILTER_ALL_TYPES": "جميع الأنواع",
  "FILTER_TYPE_PERSON": "فرد",
  "FILTER_TYPE_COMPANY": "شركة / كيان",
  "FILTER_TYPE_ASSOCIATION": "جمعية",
  "FILTER_TYPE_INSTITUTION": "مؤسسة",
  "FILTER_ALL_STATUS": "جميع الحالات",
  "FILTER_ALL_RISKS": "جميع المخاطر",
  "FILTER_RISK_HIGH": "مخاطر عالية (>=70%)",
  "FILTER_RISK_MEDIUM": "مخاطر متوسطة (40-69%)",
  "FILTER_RISK_LOW": "مخاطر منخفضة (<40%)",
  "TH_CLIENT": "العميل",
  "TH_TYPE_SECTOR": "النوع والقطاع",
  "TH_MATCHES": "تطابقات العقوبات",
  "TH_STATUS": "حالة AML (القرار)",
  "TH_ACTIONS": "إجراءات",
  "UNKNOWN_COUNTRY": "بلد غير معروف",
  "NO_SECTOR": "لا يوجد قطاع",
  "HITS": "تطابق(ات)",
  "MAX_SCORE": "أقصى درجة: ",
  "TOOLTIP_CLIENT_SHEET": "ملف العميل",
  "TOOLTIP_KYC_DOSSIER": "ملف العناية الواجبة KYC",
  "TOOLTIP_DOWNLOAD_PDF": "تحميل ورقة LCB-FT (PDF)",
  "NO_CLIENTS_FOUND": "لا يوجد عملاء يطابقون معايير التصفية.",
  "PAGINATION_SHOWING": "عرض",
  "PAGINATION_FROM": "(من ",
  "PAGINATION_TO": " إلى ",
  "PAGINATION_OUT_OF": " من ",
  "PAGINATION_CLIENTS": " عملاء)",
  "MODAL_TITLE_UBO": "تقرير تدقيق AML-CFT (للمستفيدين)",
  "MODAL_TITLE_CLIENT": "تقرير تدقيق AML-CFT (للعملاء)",
  "MODAL_SUBTITLE": "تم الإنشاء عبر JasperReports",
  "MODAL_DESC_UBO": "حدد فترة تحليل حالة AML للمستفيدين الفعليين (UBOs). إذا كانت التواريخ فارغة، سيتم إنشاء التقرير لآخر سنتين كإجراء افتراضي.",
  "MODAL_DESC_CLIENT": "حدد فترة تحليل حالة AML لعملائك. إذا كانت التواريخ فارغة، سيتم إنشاء التقرير لآخر سنتين كإجراء افتراضي.",
  "MODAL_START_DATE": "تاريخ البدء",
  "MODAL_END_DATE": "تاريخ الانتهاء",
  "MODAL_CANCEL": "إلغاء",
  "MODAL_GENERATING": "جاري الإنشاء...",
  "MODAL_DOWNLOAD": "تحميل PDF",
  "ALERTS": {
    "CONFIRM_TITLE": "تحديث الحالة؟",
    "CONFIRM_MSG": "هل أنت متأكد من تغيير حالة الامتثال لهذا العميل إلى '{{status}}'؟",
    "UPDATE_SUCCESS": "تم تحديث حالة الامتثال بنجاح.",
    "UPDATE_ERROR": "فشل في تحديث الحالة",
    "ERROR": "خطأ",
    "GENERATING_PDF": "جاري الإنشاء",
    "GENERATING_PDF_MSG": "تجهيز ورقة AML-CFT لـ {{name}}...",
    "PDF_SUCCESS": "تم تنزيل ورقة AML-CFT.",
    "PDF_ERROR": "خطأ في تنزيل التقرير",
    "LAUNCH": "بدء",
    "CLIENT_SCREENING_MSG": "جاري فحص العملاء...",
    "CLIENT_SCREENING_SUCCESS": "اكتمل فحص العملاء اليدوي بنجاح.",
    "CLIENT_SCREENING_ERROR": "فشل في بدء فحص العملاء",
    "UBO_SCREENING_MSG": "جاري فحص المستفيدين...",
    "UBO_SCREENING_SUCCESS": "اكتمل فحص المستفيدين اليدوي بنجاح.",
    "UBO_SCREENING_ERROR": "فشل في بدء فحص المستفيدين",
    "UBO_REPORT_MSG": "إنشاء تقرير تدقيق المستفيدين...",
    "CLIENT_REPORT_MSG": "إنشاء تقرير تدقيق العملاء...",
    "UBO_REPORT_SUCCESS": "تم إنشاء وتنزيل تقرير المستفيدين بنجاح.",
    "CLIENT_REPORT_SUCCESS": "تم إنشاء وتنزيل تقرير العملاء بنجاح.",
    "UBO_REPORT_ERROR": "فشل في إنشاء تقرير المستفيدين",
    "CLIENT_REPORT_ERROR": "فشل في إنشاء تقرير العملاء"
  }
};

fs.writeFileSync('d:/avo-maitrise/front/public/assets/i18n/ar.json', JSON.stringify(data, null, 2));
console.log('Updated ar.json with true Arabic texts for Phase 4');
