const fs = require('fs');

const MODEL_TRANSLATIONS = {
  en: {
    "TITLE": "List of Templates and Internal Resources",
    "SUBTITLE": "Search, filter, and manage document templates and internal policies of your firm.",
    "SEARCH_FILTERS": "Search & Filter Options",
    "SEARCH_PLACEHOLDER": "Search by name, description...",
    "ALL_CATEGORIES": "All Categories",
    "CONTRACTS": "Contracts",
    "KYC_FORMS": "KYC Forms",
    "POLICIES": "Policies",
    "INTERNAL_DOCS": "Internal Docs",
    "ALL_STATUSES": "All Statuses",
    "ACTIVE": "Active",
    "IN_REVIEW": "In Review",
    "ARCHIVED": "Archived / Obsolete",
    "DOCUMENTS_FOUND": "template document(s) found.",
    "ADD_NEW": "Add a New Template",
    "NO_MODELS": "No Document Template",
    "NO_MODELS_DESC": "No template document matches the current search filters.",
    "UPDATED": "UPD",
    "RECENT": "Recent",
    "NO_DESC": "No description provided.",
    "CATEGORY": "Category",
    "FILE": "File",
    "DOWNLOAD": "Download",
    "EDIT": "Edit",
    "DELETE": "Delete",
    "CREATE_MODAL_TITLE": "Create a New Template",
    "CREATE_MODAL_DESC": "Fill in the information below to add a new document template.",
    "FORM_TITLE": "Template Title",
    "FORM_DESC": "Description / Usage instructions",
    "FORM_FILE": "Template File",
    "FORM_FILE_HELP": "PDF, DOCX or XLSX only.",
    "BTN_CANCEL": "Cancel",
    "BTN_CREATE": "Create Template"
  },
  es: {
    "TITLE": "Lista de Plantillas y Recursos Internos",
    "SUBTITLE": "Busque, filtre y administre plantillas de documentos y políticas internas de su firma.",
    "SEARCH_FILTERS": "Opciones de Búsqueda y Filtrado",
    "SEARCH_PLACEHOLDER": "Buscar por nombre, descripción...",
    "ALL_CATEGORIES": "Todas las Categorías",
    "CONTRACTS": "Contratos",
    "KYC_FORMS": "Formularios KYC",
    "POLICIES": "Políticas",
    "INTERNAL_DOCS": "Documentos Internos",
    "ALL_STATUSES": "Todos los Estados",
    "ACTIVE": "Activo",
    "IN_REVIEW": "En Revisión",
    "ARCHIVED": "Archivado / Obsoleto",
    "DOCUMENTS_FOUND": "documento(s) de plantilla encontrado(s).",
    "ADD_NEW": "Añadir una Nueva Plantilla",
    "NO_MODELS": "Ninguna Plantilla de Documento",
    "NO_MODELS_DESC": "Ningún documento de plantilla coincide con los filtros de búsqueda actuales.",
    "UPDATED": "ACT",
    "RECENT": "Reciente",
    "NO_DESC": "No se proporcionó descripción.",
    "CATEGORY": "Categoría",
    "FILE": "Archivo",
    "DOWNLOAD": "Descargar",
    "EDIT": "Editar",
    "DELETE": "Eliminar",
    "CREATE_MODAL_TITLE": "Crear una Nueva Plantilla",
    "CREATE_MODAL_DESC": "Complete la información a continuación para agregar una nueva plantilla de documento.",
    "FORM_TITLE": "Título de la Plantilla",
    "FORM_DESC": "Descripción / Instrucciones de uso",
    "FORM_FILE": "Archivo de Plantilla",
    "FORM_FILE_HELP": "Solo PDF, DOCX o XLSX.",
    "BTN_CANCEL": "Cancelar",
    "BTN_CREATE": "Crear Plantilla"
  },
  de: {
    "TITLE": "Liste der Vorlagen und internen Ressourcen",
    "SUBTITLE": "Suchen, filtern und verwalten Sie Dokumentvorlagen und interne Richtlinien Ihrer Kanzlei.",
    "SEARCH_FILTERS": "Such- & Filteroptionen",
    "SEARCH_PLACEHOLDER": "Suche nach Name, Beschreibung...",
    "ALL_CATEGORIES": "Alle Kategorien",
    "CONTRACTS": "Verträge",
    "KYC_FORMS": "KYC-Formulare",
    "POLICIES": "Richtlinien",
    "INTERNAL_DOCS": "Interne Dokumente",
    "ALL_STATUSES": "Alle Status",
    "ACTIVE": "Aktiv",
    "IN_REVIEW": "In Überprüfung",
    "ARCHIVED": "Archiviert / Veraltet",
    "DOCUMENTS_FOUND": "Vorlagendokument(e) gefunden.",
    "ADD_NEW": "Neue Vorlage hinzufügen",
    "NO_MODELS": "Keine Dokumentvorlage",
    "NO_MODELS_DESC": "Kein Vorlagendokument entspricht den aktuellen Suchfiltern.",
    "UPDATED": "AKT",
    "RECENT": "Neueste",
    "NO_DESC": "Keine Beschreibung angegeben.",
    "CATEGORY": "Kategorie",
    "FILE": "Datei",
    "DOWNLOAD": "Herunterladen",
    "EDIT": "Bearbeiten",
    "DELETE": "Löschen",
    "CREATE_MODAL_TITLE": "Neue Vorlage erstellen",
    "CREATE_MODAL_DESC": "Füllen Sie die folgenden Informationen aus, um eine neue Dokumentvorlage hinzuzufügen.",
    "FORM_TITLE": "Vorlagentitel",
    "FORM_DESC": "Beschreibung / Nutzungsanweisungen",
    "FORM_FILE": "Vorlagendatei",
    "FORM_FILE_HELP": "Nur PDF, DOCX oder XLSX.",
    "BTN_CANCEL": "Abbrechen",
    "BTN_CREATE": "Vorlage erstellen"
  },
  it: {
    "TITLE": "Elenco dei Modelli e Risorse Interne",
    "SUBTITLE": "Cerca, filtra e gestisci i modelli di documenti e le politiche interne del tuo studio.",
    "SEARCH_FILTERS": "Opzioni di Ricerca e Filtro",
    "SEARCH_PLACEHOLDER": "Cerca per nome, descrizione...",
    "ALL_CATEGORIES": "Tutte le Categorie",
    "CONTRACTS": "Contratti",
    "KYC_FORMS": "Moduli KYC",
    "POLICIES": "Politiche",
    "INTERNAL_DOCS": "Documenti Interni",
    "ALL_STATUSES": "Tutti gli Stati",
    "ACTIVE": "Attivo",
    "IN_REVIEW": "In Revisione",
    "ARCHIVED": "Archiviato / Obsoleto",
    "DOCUMENTS_FOUND": "documento/i modello trovato/i.",
    "ADD_NEW": "Aggiungi un Nuovo Modello",
    "NO_MODELS": "Nessun Modello di Documento",
    "NO_MODELS_DESC": "Nessun documento modello corrisponde agli attuali filtri di ricerca.",
    "UPDATED": "AGG",
    "RECENT": "Recente",
    "NO_DESC": "Nessuna descrizione fornita.",
    "CATEGORY": "Categoria",
    "FILE": "File",
    "DOWNLOAD": "Scarica",
    "EDIT": "Modifica",
    "DELETE": "Elimina",
    "CREATE_MODAL_TITLE": "Crea un Nuovo Modello",
    "CREATE_MODAL_DESC": "Compila le informazioni sottostanti per aggiungere un nuovo modello di documento.",
    "FORM_TITLE": "Titolo del Modello",
    "FORM_DESC": "Descrizione / Istruzioni per l'uso",
    "FORM_FILE": "File del Modello",
    "FORM_FILE_HELP": "Solo PDF, DOCX o XLSX.",
    "BTN_CANCEL": "Annulla",
    "BTN_CREATE": "Crea Modello"
  }
};

const basePath = 'd:/avo-maitrise/front/public/assets/i18n';

for (const [lang, translations] of Object.entries(MODEL_TRANSLATIONS)) {
  const filePath = `${basePath}/${lang}.json`;
  if (fs.existsSync(filePath)) {
    const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));
    data['MODEL'] = translations;
    fs.writeFileSync(filePath, JSON.stringify(data, null, 2));
    console.log(`Updated ${lang}.json for MODEL`);
  }
}
