const fs = require('fs');
const filePath = 'd:/avo-maitrise/front/public/assets/i18n/ar.json';

const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));

const ARABIC_PHASE3 = {
  "DOSSIER_DETAILS": {
    "TITLE": "ملف القضية",
    "MATTER": "القضية",
    "STATUS_NOT_DEFINED": "حالة غير محددة",
    "PRIORITY_NOT_DEFINED": "أولوية غير محددة",
    "ACTIONS": "إجراءات",
    "BREADCRUMB_DOSSIERS": "القضايا",
    "BREADCRUMB_DETAILS": "التفاصيل",
    "TAB_OVERVIEW": "نظرة عامة",
    "TAB_DOCUMENTS": "المستندات",
    "TAB_EVENTS": "الأحداث والمواعيد",
    "TAB_TASKS": "المهام",
    "TAB_NOTES": "الملاحظات",
    "TAB_CONTACTS": "جهات الاتصال والأدوار",
    "TAB_SERVICES": "الخدمات",
    "TAB_JOURNAL": "سجل النشاط"
  },
  "DOSSIER_FORM": {
    "TITLE_NEW": "إنشاء قضية جديدة",
    "TITLE_EDIT": "تعديل القضية",
    "SUBTITLE": "املأ التفاصيل لإدارة هذه القضية.",
    "REF": "مرجع القضية",
    "REF_HELP": "يتم إنشاؤه تلقائيًا إذا تُرك فارغًا.",
    "TITLE_LABEL": "العنوان / اسم القضية",
    "DESC_LABEL": "وصف داخلي / الموضوع",
    "CLIENT_LABEL": "العميل الرئيسي",
    "STATUS_LABEL": "الحالة الحالية",
    "STATUS_PLACEHOLDER": "اختر حالة",
    "PRIORITY_LABEL": "الأولوية",
    "PRIORITY_PLACEHOLDER": "اختر أولوية",
    "LEGAL_DOMAIN_LABEL": "المجال القانوني",
    "LEGAL_DOMAIN_PLACEHOLDER": "اختر مجالاً",
    "TEAM_LABEL": "الفريق المعين",
    "TEAM_PLACEHOLDER": "اختر محامياً أو أكثر",
    "START_DATE": "تاريخ الفتح",
    "ESTIMATED_END_DATE": "تاريخ الإغلاق المقدر",
    "BILLING_MODE_LABEL": "طريقة الفوترة",
    "BILLING_HOURLY": "سعر بالساعة",
    "BILLING_FLAT": "سعر ثابت",
    "BILLING_SUBSCRIPTION": "اشتراك",
    "HOURLY_RATE": "سعر مخصص للساعة",
    "BUDGET_CAP": "الحد الأقصى للميزانية (تنبيه)",
    "CANCEL": "إلغاء",
    "UPDATE": "تحديث القضية",
    "SAVE": "إنشاء القضية",
    "REMOVE": "إزالة",
    "MANAGE_TEAM": "إدارة الفريق",
    "SELECT_CLIENT": "اختر عميلاً",
    "SELECT": "اختيار"
  },
  "DOSSIER_SELECTION": {
    "TITLE": "اختر قضية",
    "SEARCH_PLACEHOLDER": "ابحث بالمرجع أو العنوان...",
    "NO_MATTER_FOUND": "لم يتم العثور على قضايا.",
    "CONFIRM": "تأكيد"
  },
  "DOMAIN_SELECTION": {
    "TITLE": "اختر مجالاً قانونياً",
    "SEARCH_PLACEHOLDER": "ابحث بالتسمية أو الرمز...",
    "NO_DOMAIN_FOUND": "لم يتم العثور على مجالات قانونية.",
    "CONFIRM": "تأكيد"
  },
  "USER_SELECTION": {
    "TITLE": "اختر أعضاء الفريق",
    "SEARCH_PLACEHOLDER": "ابحث بالاسم أو البريد الإلكتروني...",
    "NO_USER_FOUND": "لم يتم العثور على مستخدمين.",
    "CONFIRM": "تأكيد الاختيار"
  },
  "CLIENT_SELECTION": {
    "TITLE": "اختر عميلاً",
    "SEARCH_PLACEHOLDER": "ابحث بالاسم أو اللقب أو البريد...",
    "NO_CLIENT_FOUND": "لم يتم العثور على عملاء.",
    "CONFIRM": "تأكيد"
  },
  "DOSSIER_VUE": {
    "NEXT_DEADLINE": "الموعد النهائي القادم",
    "PREP_HEARING": "جلسة تحضيرية",
    "DATE_TIME": "في 10/05/2025 الساعة 09:00",
    "COURT": "المحكمة الجنائية",
    "VIEW_DETAILS": "عرض التفاصيل ←",
    "TEAM": "الفريق",
    "LEAD_PARTNER": "الشريك الرئيسي",
    "ASSOCIATE": "مساعد",
    "NO_TEAM": "لا يوجد أعضاء معينين"
  },
  "DOSSIER_INFO": {
    "DETAILED_SUMMARY": "ملخص مفصل",
    "NO_DESC": "لا يوجد وصف متاح لهذه القضية.",
    "TYPE": "النوع",
    "RECENT_ACTIVITY": "سجل النشاط الأخير",
    "CLIENT_INFO": "معلومات العميل",
    "VIEW_FILE": "عرض الملف",
    "INDIVIDUAL": "فرد",
    "COMPANY": "شركة",
    "NO_CLIENT": "لا يوجد عميل مرتبط بهذه القضية.",
    "ADMIN_DETAILS": "تفاصيل إدارية",
    "LEAD_LAWYER": "المحامي الرئيسي:",
    "ASSOCIATE_LAWYERS": "المحامون المساعدون:",
    "OPENING_DATE": "تاريخ الفتح:",
    "BILLING_MODE": "طريقة الفوترة:",
    "TOTAL_HOURS": "إجمالي الساعات (للفوترة):",
    "NO_DOSSIER": "لم يتم اختيار قضية."
  },
  "MATTER_ACTIVITY": {
    "FROM": "من",
    "TO": "إلى",
    "REFRESH": "تحديث",
    "DATE": "التاريخ",
    "AUTHOR": "المؤلف",
    "ACTION": "الإجراء",
    "TYPE": "النوع",
    "DESCRIPTION": "الوصف",
    "NO_ACTIVITY": "لم يتم العثور على نشاط لهذه الفترة.",
    "PREV": "السابق",
    "NEXT": "التالي",
    "SHOWING": "عرض",
    "TO_LOWER": "إلى",
    "OUT_OF": "من أصل",
    "RESULTS": "النتائج"
  },
  "TASK_MANAGER": {
    "TITLE": "إدارة المهام",
    "SUBTITLE": "تتبع تقدم الإجراءات المتعلقة بهذه القضية.",
    "NEW_TASK": "مهمة جديدة",
    "COMPLETION_RATE": "معدل الإنجاز",
    "COMPLETED": "مكتمل",
    "SEARCH_PLACEHOLDER": "البحث عن مهمة بالعنوان...",
    "ALL_CATEGORIES": "جميع الفئات",
    "ALL_STATUSES": "جميع الحالات",
    "MY_URGENT_TASKS": "مهامي العاجلة",
    "NO_TASK_FOUND": "لم يتم العثور على مهام",
    "MODIFY_FILTERS": "قم بتعديل فلاترك أو أنشئ مهمة جديدة.",
    "OVERDUE": "متأخر",
    "INFO_TAB": "المعلومات",
    "ACTIVITY_TAB": "النشاط",
    "ESTIMATED_TIME": "الوقت المقدر:",
    "VIEW": "عرض",
    "EDIT": "تعديل",
    "NO_HISTORY": "لا يوجد تاريخ",
    "WRITE_COMMENT": "اكتب تعليقاً...",
    "ADD": "إضافة"
  },
  "TASK_DIALOG": {
    "EDIT_TASK": "تعديل المهمة",
    "NEW_TASK": "مهمة جديدة",
    "DETAILS": "التفاصيل",
    "COMMENTS": "التعليقات",
    "TITLE_LABEL": "عنوان المهمة",
    "TITLE_PLACEHOLDER": "مثال: صياغة الاستنتاجات...",
    "DESC_LABEL": "الوصف",
    "DESC_PLACEHOLDER": "تفاصيل إضافية...",
    "CATEGORY_LABEL": "الفئة",
    "CATEGORY_PLACEHOLDER": "اختر فئة",
    "STATUS_LABEL": "الحالة الأولية",
    "STATUS_PLACEHOLDER": "اختر حالة",
    "PRIORITY_LABEL": "الأولوية",
    "PRIORITY_LOW": "منخفضة",
    "PRIORITY_NORMAL": "عادية",
    "PRIORITY_HIGH": "عالية",
    "PRIORITY_URGENT": "عاجلة",
    "ASSIGNEE_LABEL": "مُسند إلى",
    "REMOVE": "إزالة",
    "MANAGE_ASSIGNEES": "إدارة المسند إليهم",
    "DUE_DATE_LABEL": "تاريخ الاستحقاق",
    "ESTIMATED_TIME_LABEL": "الوقت المقدر (بالدقائق)",
    "ESTIMATED_TIME_PLACEHOLDER": "مثال: 60",
    "NO_COMMENTS": "لا توجد تعليقات لهذه المهمة.",
    "ME_LAWYER": "أنا (المحامي)",
    "NEW_COMMENT_PLACEHOLDER": "إضافة تعليق جديد...",
    "CLOSE": "إغلاق",
    "UPDATE": "تحديث",
    "SAVE": "حفظ"
  },
  "PRESTATIONS": {
    "TITLE": "الخدمات",
    "GENERATE_INVOICE": "إنشاء فاتورة",
    "ADD_PRESTATION": "إضافة خدمة",
    "DATE": "التاريخ",
    "SERVICE_TYPE": "نوع الخدمة",
    "STATUS": "الحالة",
    "LAWYER": "المحامي",
    "DETAILS": "التفاصيل",
    "DURATION": "المدة (دقيقة)",
    "ACTIONS": "إجراءات",
    "UNASSIGNED": "غير معين",
    "EDIT": "تعديل",
    "NO_PRESTATION": "لم يتم تسجيل أي خدمات لهذه القضية.",
    "MODAL_TITLE_EDIT": "تعديل الخدمة",
    "MODAL_TITLE_ADD": "إضافة خدمة",
    "SERVICE_TYPE_LABEL": "نوع الخدمة *",
    "SERVICE_TYPE_PLACEHOLDER": "اختر نوعاً",
    "STATUS_LABEL": "الحالة *",
    "DESC_LABEL": "الوصف (التفاصيل) *",
    "DESC_PLACEHOLDER": "وصف الخدمة...",
    "DURATION_LABEL": "المدة (بالدقائق) *",
    "LAWYER_LABEL": "نُفذ بواسطة (المحامي) *",
    "MYSELF": "نفسي",
    "SELECT": "تحديد",
    "ASSIGN_TO_ME_TITLE": "تعيين لنفسي",
    "CANCEL": "إلغاء",
    "UPDATE": "تحديث",
    "SAVE": "حفظ"
  },
  "DOCUMENT": {
    "UPLOAD": "تحميل مستند جديد",
    "SEARCH": "ابحث بالعنوان أو المحتوى...",
    "FILTER_TYPE": "تصفية حسب النوع",
    "CONTRACTS": "العقود",
    "PROCEDURES": "الإجراءات",
    "EVIDENCE": "أدلة الخصوم",
    "DOC_TITLE": "عنوان المستند",
    "TYPE": "النوع",
    "ADDED_BY": "تمت الإضافة بواسطة",
    "UPLOAD_DATE": "تاريخ التحميل",
    "SIZE": "الحجم",
    "ACTIONS": "إجراءات",
    "NO_TITLE": "مستند بدون عنوان",
    "UNKNOWN": "غير معروف",
    "NA": "غير متاح",
    "DOWNLOAD": "تحميل",
    "DELETE": "حذف",
    "NO_DOCUMENT": "لا توجد مستندات متاحة حاليًا."
  },
  "DOCUMENT_DIALOG": {
    "DOC_TITLE_LABEL": "عنوان المستند",
    "FILE_LABEL": "الملف",
    "CHANGE_FILE": "تغيير الملف",
    "UPLOAD_FILE": "تحميل ملف",
    "OR_DRAG_DROP": "أو اسحب وأفلت",
    "EXISTING_FILE": "ملف موجود",
    "NOTES_LABEL": "ملاحظات (اختياري)",
    "CANCEL": "إلغاء",
    "SAVE": "حفظ",
    "UPLOAD": "تحميل"
  },
  "EVENEMENT": {
    "ADD_EVENT": "إضافة حدث جديد",
    "SEARCH_PLACEHOLDER": "البحث حسب التاريخ، الموقع، أو المشارك...",
    "DATE_TIME": "التاريخ/الوقت:",
    "PARTICIPANTS": "المشاركون:",
    "NONE": "لا أحد",
    "LOCATION": "الموقع:",
    "OTHER_PARTICIPANTS": "مشاركون آخرون:",
    "PERSONS": "شخص (أشخاص)",
    "NO_EVENTS": "لا توجد أحداث مجدولة لهذه القضية.",
    "SHOW_ALL": "عرض كل الأحداث أو التقويم الكامل",
    "PERIOD": "الفترة",
    "FROM": "من:",
    "TO": "إلى:",
    "ALL_DAY": "طوال اليوم",
    "NOT_SPECIFIED": "غير محدد",
    "DESC_NOTES": "الوصف / ملاحظات",
    "NO_DESC": "لم يتم تقديم وصف.",
    "STATUS_CURRENT": "الحالة الحالية",
    "CREATED_AT": "تم الإنشاء في:",
    "UPDATED_AT": "آخر تحديث:"
  },
  "EVENEMENT_DIALOG": {
    "TITLE": "جدولة حدث / موعد جديد",
    "EVENT_OBJECT": "موضوع الحدث",
    "EVENT_OBJECT_PLACEHOLDER": "مثال: جلسة استماع أمام قاضي التحقيق...",
    "CATEGORY": "الفئة",
    "CATEGORY_PLACEHOLDER": "اختر فئة",
    "START": "البداية",
    "END": "النهاية",
    "INTERVENANTS": "المشاركون (رئيسي / آخرون)",
    "REMOVE": "إزالة",
    "SELECT_MANAGE_INTERVENANTS": "تحديد أو إدارة المشاركين",
    "LOCATION": "المكان (فعلي أو عبر الفيديو)",
    "LOCATION_PLACEHOLDER": "مثال: المحكمة - الغرفة 3، رابط Teams...",
    "DESC_NOTES": "الوصف / ملاحظات",
    "DESC_NOTES_PLACEHOLDER": "تفاصيل إضافية حول الجلسة...",
    "ACTIVATE_REMINDER": "تفعيل التذكير",
    "MINUTES_BEFORE": "دقيقة قبل الحدث",
    "CANCEL": "إلغاء",
    "SAVE_EVENT": "حفظ الحدث"
  }
};

Object.assign(data, ARABIC_PHASE3);

fs.writeFileSync(filePath, JSON.stringify(data, null, 2));
console.log('Updated ar.json with true Arabic translations for Phase 3.');
