const fs = require('fs');

const CRM_TRANSLATIONS = {
  en: {
    "BREADCRUMB_DASHBOARD": "Dashboard",
    "BREADCRUMB_CLIENTS": "Client Management",
    "DIRECTORY": "Directory",
    "CLIENTS_CONTACTS": "Clients & Contacts",
    "SUBTITLE": "Manage your client database with real-time AML monitoring and rigorous KYC compliance tracking.",
    "ALERTS_CRITICAL": "Critical AML Alerts",
    "NO_ALERTS": "No AML Alerts",
    "NEW_CLIENT": "New Client",
    "TAB_ALL": "All Clients",
    "TAB_PERSONNE": "Individuals",
    "TAB_SOCIETE": "Companies",
    "TAB_ASSOCIATION": "Associations",
    "TAB_INSTITUTION": "Institutions",
    "SEARCH_PLACEHOLDER": "Search by name, ID, or country...",
    "FILTER_ALL_TYPES": "All Types",
    "FILTER_PERSON": "Individual",
    "FILTER_COMPANY": "Company / Entity",
    "FILTER_ASSOCIATION": "Association",
    "FILTER_INSTITUTION": "Institution",
    "FILTER_ALL_RISKS": "AML Risk (All)",
    "RISK_HIGH": "High Risk",
    "RISK_MEDIUM": "Medium Risk",
    "RISK_LOW": "Low Risk",
    "LOADING": "Loading client directory...",
    "NO_CLIENT_FOUND": "No client found",
    "NO_CLIENT_DESC": "Start by adding your first client to the directory.",
    "CREATE_CLIENT": "Create a Client",
    "SHOWING": "Showing",
    "TO": "to",
    "OUT_OF": "out of",
    "MATTERS_LC": "cases"
  },
  es: {
    "BREADCRUMB_DASHBOARD": "Panel de Control",
    "BREADCRUMB_CLIENTS": "Gestión de Clientes",
    "DIRECTORY": "Directorio",
    "CLIENTS_CONTACTS": "Clientes y Contactos",
    "SUBTITLE": "Gestione su base de datos de clientes con monitoreo AML en tiempo real y seguimiento riguroso de cumplimiento KYC.",
    "ALERTS_CRITICAL": "Alertas Críticas AML",
    "NO_ALERTS": "Sin Alertas AML",
    "NEW_CLIENT": "Nuevo Cliente",
    "TAB_ALL": "Todos los Clientes",
    "TAB_PERSONNE": "Personas Físicas",
    "TAB_SOCIETE": "Empresas",
    "TAB_ASSOCIATION": "Asociaciones",
    "TAB_INSTITUTION": "Instituciones",
    "SEARCH_PLACEHOLDER": "Buscar por nombre, ID o país...",
    "FILTER_ALL_TYPES": "Todos los Tipos",
    "FILTER_PERSON": "Persona Física",
    "FILTER_COMPANY": "Empresa / Entidad",
    "FILTER_ASSOCIATION": "Asociación",
    "FILTER_INSTITUTION": "Institución",
    "FILTER_ALL_RISKS": "Riesgo AML (Todos)",
    "RISK_HIGH": "Riesgo Alto",
    "RISK_MEDIUM": "Riesgo Medio",
    "RISK_LOW": "Riesgo Bajo",
    "LOADING": "Cargando directorio de clientes...",
    "NO_CLIENT_FOUND": "No se encontraron clientes",
    "NO_CLIENT_DESC": "Comience agregando su primer cliente al directorio.",
    "CREATE_CLIENT": "Crear un Cliente",
    "SHOWING": "Mostrando",
    "TO": "a",
    "OUT_OF": "de",
    "MATTERS_LC": "casos"
  },
  de: {
    "BREADCRUMB_DASHBOARD": "Dashboard",
    "BREADCRUMB_CLIENTS": "Kundenmanagement",
    "DIRECTORY": "Verzeichnis",
    "CLIENTS_CONTACTS": "Kunden & Kontakte",
    "SUBTITLE": "Verwalten Sie Ihre Kundendatenbank mit Echtzeit-AML-Überwachung und strenger KYC-Compliance-Verfolgung.",
    "ALERTS_CRITICAL": "Kritische AML-Warnungen",
    "NO_ALERTS": "Keine AML-Warnungen",
    "NEW_CLIENT": "Neuer Kunde",
    "TAB_ALL": "Alle Kunden",
    "TAB_PERSONNE": "Natürliche Personen",
    "TAB_SOCIETE": "Unternehmen",
    "TAB_ASSOCIATION": "Verbände",
    "TAB_INSTITUTION": "Institutionen",
    "SEARCH_PLACEHOLDER": "Suche nach Name, ID oder Land...",
    "FILTER_ALL_TYPES": "Alle Typen",
    "FILTER_PERSON": "Natürliche Person",
    "FILTER_COMPANY": "Unternehmen / Einrichtung",
    "FILTER_ASSOCIATION": "Verband",
    "FILTER_INSTITUTION": "Institution",
    "FILTER_ALL_RISKS": "AML-Risiko (Alle)",
    "RISK_HIGH": "Hohes Risiko",
    "RISK_MEDIUM": "Mittleres Risiko",
    "RISK_LOW": "Geringes Risiko",
    "LOADING": "Kundenverzeichnis wird geladen...",
    "NO_CLIENT_FOUND": "Kein Kunde gefunden",
    "NO_CLIENT_DESC": "Beginnen Sie damit, Ihren ersten Kunden zum Verzeichnis hinzuzufügen.",
    "CREATE_CLIENT": "Kunden erstellen",
    "SHOWING": "Zeige",
    "TO": "bis",
    "OUT_OF": "von",
    "MATTERS_LC": "Fälle"
  },
  it: {
    "BREADCRUMB_DASHBOARD": "Dashboard",
    "BREADCRUMB_CLIENTS": "Gestione Clienti",
    "DIRECTORY": "Elenco",
    "CLIENTS_CONTACTS": "Clienti e Contatti",
    "SUBTITLE": "Gestisci il tuo database clienti con monitoraggio AML in tempo reale e rigoroso tracciamento della conformità KYC.",
    "ALERTS_CRITICAL": "Avvisi Critici AML",
    "NO_ALERTS": "Nessun Avviso AML",
    "NEW_CLIENT": "Nuovo Cliente",
    "TAB_ALL": "Tutti i Clienti",
    "TAB_PERSONNE": "Persone Fisiche",
    "TAB_SOCIETE": "Società",
    "TAB_ASSOCIATION": "Associazioni",
    "TAB_INSTITUTION": "Istituzioni",
    "SEARCH_PLACEHOLDER": "Cerca per nome, ID o paese...",
    "FILTER_ALL_TYPES": "Tutti i Tipi",
    "FILTER_PERSON": "Persona Fisica",
    "FILTER_COMPANY": "Società / Ente",
    "FILTER_ASSOCIATION": "Associazione",
    "FILTER_INSTITUTION": "Istituzione",
    "FILTER_ALL_RISKS": "Rischio AML (Tutti)",
    "RISK_HIGH": "Alto Rischio",
    "RISK_MEDIUM": "Rischio Medio",
    "RISK_LOW": "Basso Rischio",
    "LOADING": "Caricamento elenco clienti...",
    "NO_CLIENT_FOUND": "Nessun cliente trovato",
    "NO_CLIENT_DESC": "Inizia aggiungendo il tuo primo cliente all'elenco.",
    "CREATE_CLIENT": "Crea un Cliente",
    "SHOWING": "In mostra",
    "TO": "a",
    "OUT_OF": "su",
    "MATTERS_LC": "casi"
  }
};

const basePath = 'd:/avo-maitrise/front/public/assets/i18n';

for (const [lang, translations] of Object.entries(CRM_TRANSLATIONS)) {
  const filePath = `${basePath}/${lang}.json`;
  if (fs.existsSync(filePath)) {
    const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));
    data['CRM'] = translations;
    fs.writeFileSync(filePath, JSON.stringify(data, null, 2));
    console.log(`Updated ${lang}.json for CRM`);
  }
}
