const fs = require('fs');

const TRANSLATIONS = {
  en: {
    CLIENT_FORM: {
      "TITLE_EDIT":"Edit","TITLE_NEW":"New","TITLE_CLIENT":"Client","TITLE_PHYSICAL":"Individual","SUBTITLE_PHYSICAL":"Identification & Individual Compliance","TITLE_MORAL":"Company","SUBTITLE_MORAL":"Corporate Identification & KYC","TITLE_ASSOCIATION":"Association","SUBTITLE_ASSOCIATION":"Non-profit Organization Identification","TITLE_INSTITUTION":"Institution","SUBTITLE_INSTITUTION":"Institutional Organization Identification","ASSOC_NAME":"Association Name","INST_NAME":"Institution Designation","FISCAL_ID_APP":"Tax ID (if applicable)","CREATE_ASSOC":"Create Association","CREATE_INST":"Create Institution","CONTACT_HQ":"Contact & HQ","SUBTITLE":"Entity Types & KYC Management","ENTITY_TYPE":"Entity Type","CONTACT_INFO":"Contact Information","EMAIL":"Main Email","EMAIL_INVALID":"Invalid email address","EMAIL_REQUIRED":"Email is required","PHONE":"Phone","PHONE_REQUIRED":"Phone is required","ADDRESS":"Address","COUNTRY":"Country","COUNTRY_REQUIRED":"Country is required","SECTOR":"Business Sector","SECTOR_SELECT":"Select a sector","SECTOR_REQUIRED":"Business sector is required","IDENTITY_DETAILS":"Identity Details","FIRST_NAME":"First Name","FIRST_NAME_REQUIRED":"First name is required","LAST_NAME":"Last Name","LAST_NAME_REQUIRED":"Last name is required","NATIONALITY":"Nationality","PASSPORT":"ID / Passport","BIRTH_DATE":"Date of Birth","COMPANY_INFO":"Company Information","COMMERCIAL_NAME":"Trade Name","COMMERCIAL_NAME_REQUIRED":"Trade name is required","LEGAL_FORM":"Legal Form","RC":"Trade Register No.","RC_REQUIRED":"Trade Register No. is required","FISCAL_ID":"Tax ID No.","ORG_DETAILS":"Organization Details","ORG_NAME":"Organization Name","ORG_NAME_REQUIRED":"Organization name is required","NATIONAL_REG":"National Register No.","NATIONAL_REG_REQUIRED":"National Register No. is required","LEGAL_REP":"Legal Representative","REP_LAST_NAME":"Representative Last Name","REP_FIRST_NAME":"Representative First Name","UBO_TITLE":"Ultimate Beneficial Owners (UBO)","ADD":"Add","UBO_FULL_NAME":"Full Name","UBO_OWNERSHIP":"Ownership (%)","UBO_ROLE":"Role","CONTACT_POINTS":"Contact Points","OCCUPATION":"Occupation","KYC_DOCS":"KYC Documents","ADD_DOC":"Add a document","CANCEL":"Cancel","SAVE_CHANGES":"Save changes","CREATE_CLIENT":"Create Client"
    },
    CLIENT_DETAILS: {
      "NO_ID":"No client ID provided.","LOAD_ERROR":"Unable to load client information.","LOAD_ERROR_GENERIC":"An error occurred while loading data.","INDIVIDUAL":"Individual","COMPANY":"Company","NOT_PROVIDED":"Not provided","COMPLIANCE_SHEET":"Compliance Sheet","CREATE_DOSSIER":"Create a Case","ACTIVE_DOSSIERS":"Active Cases","REFERENCE":"Reference","TITLE":"Title","OPEN_DATE":"Opening Date","ACTION":"Action","UNTITLED":"Untitled","VIEW":"View","NO_DOSSIERS":"No cases found for this client.","AML_STATUS":"AML/CFT Status","GLOBAL_STATUS":"Global Status","UNKNOWN":"Unknown","LAST_VERIFICATION":"Last verification","NEVER":"Never","NO_AML":"No compliance verification performed.","START_EVALUATION":"Start evaluation →","BILLING":"Billing","DRAFT":"Draft","DETAILS":"Details","NO_INVOICES":"No invoices issued.","INVOICE_STATUS_PAID":"Paid","INVOICE_STATUS_DRAFT":"Draft","INVOICE_STATUS_SENT":"Sent","INVOICE_STATUS_OVERDUE":"Overdue","INVOICE_STATUS_PARTIAL":"Partial"
    }
  },
  es: {
    CLIENT_FORM: {
      "TITLE_EDIT":"Editar","TITLE_NEW":"Nuevo","TITLE_CLIENT":"Cliente","TITLE_PHYSICAL":"Persona Física","SUBTITLE_PHYSICAL":"Identificación y Cumplimiento Individual","TITLE_MORAL":"Empresa","SUBTITLE_MORAL":"Identificación Corporativa y KYC","TITLE_ASSOCIATION":"Asociación","SUBTITLE_ASSOCIATION":"Identificación de Organización sin fines de lucro","TITLE_INSTITUTION":"Institución","SUBTITLE_INSTITUTION":"Identificación de Organización Institucional","ASSOC_NAME":"Nombre de la Asociación","INST_NAME":"Designación de la Institución","FISCAL_ID_APP":"Identificación Fiscal (si aplica)","CREATE_ASSOC":"Crear Asociación","CREATE_INST":"Crear Institución","CONTACT_HQ":"Contacto y Sede","SUBTITLE":"Tipos de Entidad y Gestión de KYC","ENTITY_TYPE":"Tipo de Entidad","CONTACT_INFO":"Información de Contacto","EMAIL":"Correo Principal","EMAIL_INVALID":"Correo electrónico no válido","EMAIL_REQUIRED":"El correo es obligatorio","PHONE":"Teléfono","PHONE_REQUIRED":"El teléfono es obligatorio","ADDRESS":"Dirección","COUNTRY":"País","COUNTRY_REQUIRED":"El país es obligatorio","SECTOR":"Sector de Actividad","SECTOR_SELECT":"Seleccione un sector","SECTOR_REQUIRED":"El sector de actividad es obligatorio","IDENTITY_DETAILS":"Detalles de Identidad","FIRST_NAME":"Nombre","FIRST_NAME_REQUIRED":"El nombre es obligatorio","LAST_NAME":"Apellido","LAST_NAME_REQUIRED":"El apellido es obligatorio","NATIONALITY":"Nacionalidad","PASSPORT":"ID / Pasaporte","BIRTH_DATE":"Fecha de Nacimiento","COMPANY_INFO":"Información de la Empresa","COMMERCIAL_NAME":"Nombre Comercial","COMMERCIAL_NAME_REQUIRED":"El nombre comercial es obligatorio","LEGAL_FORM":"Forma Legal","RC":"Nº Registro Comercial","RC_REQUIRED":"El Nº de Registro Comercial es obligatorio","FISCAL_ID":"Nº de Identificación Fiscal","ORG_DETAILS":"Detalles de la Organización","ORG_NAME":"Nombre de la Organización","ORG_NAME_REQUIRED":"El nombre de la organización es obligatorio","NATIONAL_REG":"Nº Registro Nacional","NATIONAL_REG_REQUIRED":"El Nº de Registro Nacional es obligatorio","LEGAL_REP":"Representante Legal","REP_LAST_NAME":"Apellido del Representante","REP_FIRST_NAME":"Nombre del Representante","UBO_TITLE":"Beneficiarios Reales (UBO)","ADD":"Añadir","UBO_FULL_NAME":"Nombre Completo","UBO_OWNERSHIP":"Propiedad (%)","UBO_ROLE":"Rol","CONTACT_POINTS":"Puntos de Contacto","OCCUPATION":"Ocupación","KYC_DOCS":"Documentos KYC","ADD_DOC":"Añadir un documento","CANCEL":"Cancelar","SAVE_CHANGES":"Guardar cambios","CREATE_CLIENT":"Crear Cliente"
    },
    CLIENT_DETAILS: {
      "NO_ID":"No se proporcionó ID de cliente.","LOAD_ERROR":"No se pudo cargar la información del cliente.","LOAD_ERROR_GENERIC":"Ocurrió un error al cargar los datos.","INDIVIDUAL":"Persona Física","COMPANY":"Empresa","NOT_PROVIDED":"No proporcionado","COMPLIANCE_SHEET":"Hoja de Cumplimiento","CREATE_DOSSIER":"Crear Expediente","ACTIVE_DOSSIERS":"Expedientes Activos","REFERENCE":"Referencia","TITLE":"Título","OPEN_DATE":"Fecha de Apertura","ACTION":"Acción","UNTITLED":"Sin Título","VIEW":"Ver","NO_DOSSIERS":"No se encontraron expedientes para este cliente.","AML_STATUS":"Estado AML/CFT","GLOBAL_STATUS":"Estado Global","UNKNOWN":"Desconocido","LAST_VERIFICATION":"Última verificación","NEVER":"Nunca","NO_AML":"No se ha realizado ninguna verificación de cumplimiento.","START_EVALUATION":"Iniciar evaluación →","BILLING":"Facturación","DRAFT":"Borrador","DETAILS":"Detalles","NO_INVOICES":"No se han emitido facturas.","INVOICE_STATUS_PAID":"Pagada","INVOICE_STATUS_DRAFT":"Borrador","INVOICE_STATUS_SENT":"Enviada","INVOICE_STATUS_OVERDUE":"Atrasada","INVOICE_STATUS_PARTIAL":"Parcial"
    }
  },
  de: {
    CLIENT_FORM: {
      "TITLE_EDIT":"Bearbeiten","TITLE_NEW":"Neu","TITLE_CLIENT":"Kunde","TITLE_PHYSICAL":"Natürliche Person","SUBTITLE_PHYSICAL":"Identifikation & Individuelle Compliance","TITLE_MORAL":"Unternehmen","SUBTITLE_MORAL":"Unternehmensidentifikation & KYC","TITLE_ASSOCIATION":"Verband","SUBTITLE_ASSOCIATION":"Identifikation einer gemeinnützigen Organisation","TITLE_INSTITUTION":"Institution","SUBTITLE_INSTITUTION":"Identifikation einer institutionellen Organisation","ASSOC_NAME":"Verbandsname","INST_NAME":"Institutionsbezeichnung","FISCAL_ID_APP":"Steuer-ID (falls zutreffend)","CREATE_ASSOC":"Verband erstellen","CREATE_INST":"Institution erstellen","CONTACT_HQ":"Kontakt & Hauptsitz","SUBTITLE":"Entitätstypen & KYC-Management","ENTITY_TYPE":"Entitätstyp","CONTACT_INFO":"Kontaktinformationen","EMAIL":"Haupt-E-Mail","EMAIL_INVALID":"Ungültige E-Mail-Adresse","EMAIL_REQUIRED":"E-Mail ist erforderlich","PHONE":"Telefon","PHONE_REQUIRED":"Telefon ist erforderlich","ADDRESS":"Adresse","COUNTRY":"Land","COUNTRY_REQUIRED":"Land ist erforderlich","SECTOR":"Wirtschaftszweig","SECTOR_SELECT":"Sektor auswählen","SECTOR_REQUIRED":"Wirtschaftszweig ist erforderlich","IDENTITY_DETAILS":"Identitätsdetails","FIRST_NAME":"Vorname","FIRST_NAME_REQUIRED":"Vorname ist erforderlich","LAST_NAME":"Nachname","LAST_NAME_REQUIRED":"Nachname ist erforderlich","NATIONALITY":"Nationalität","PASSPORT":"Ausweis / Reisepass","BIRTH_DATE":"Geburtsdatum","COMPANY_INFO":"Unternehmensinformationen","COMMERCIAL_NAME":"Handelsname","COMMERCIAL_NAME_REQUIRED":"Handelsname ist erforderlich","LEGAL_FORM":"Rechtsform","RC":"Handelsregisternummer","RC_REQUIRED":"Handelsregisternummer ist erforderlich","FISCAL_ID":"Steuer-ID-Nr.","ORG_DETAILS":"Organisationsdetails","ORG_NAME":"Organisationsname","ORG_NAME_REQUIRED":"Organisationsname ist erforderlich","NATIONAL_REG":"Nationale Registernummer","NATIONAL_REG_REQUIRED":"Nationale Registernummer ist erforderlich","LEGAL_REP":"Gesetzlicher Vertreter","REP_LAST_NAME":"Nachname des Vertreters","REP_FIRST_NAME":"Vorname des Vertreters","UBO_TITLE":"Wirtschaftlich Berechtigte (UBO)","ADD":"Hinzufügen","UBO_FULL_NAME":"Vollständiger Name","UBO_OWNERSHIP":"Eigentum (%)","UBO_ROLE":"Rolle","CONTACT_POINTS":"Kontaktpunkte","OCCUPATION":"Beruf","KYC_DOCS":"KYC-Dokumente","ADD_DOC":"Dokument hinzufügen","CANCEL":"Abbrechen","SAVE_CHANGES":"Änderungen speichern","CREATE_CLIENT":"Kunden erstellen"
    },
    CLIENT_DETAILS: {
      "NO_ID":"Keine Kunden-ID angegeben.","LOAD_ERROR":"Kundeninformationen konnten nicht geladen werden.","LOAD_ERROR_GENERIC":"Beim Laden der Daten ist ein Fehler aufgetreten.","INDIVIDUAL":"Natürliche Person","COMPANY":"Unternehmen","NOT_PROVIDED":"Nicht angegeben","COMPLIANCE_SHEET":"Compliance-Datenblatt","CREATE_DOSSIER":"Akte erstellen","ACTIVE_DOSSIERS":"Aktive Akten","REFERENCE":"Referenz","TITLE":"Titel","OPEN_DATE":"Eröffnungsdatum","ACTION":"Aktion","UNTITLED":"Ohne Titel","VIEW":"Ansehen","NO_DOSSIERS":"Keine Akten für diesen Kunden gefunden.","AML_STATUS":"AML/CFT-Status","GLOBAL_STATUS":"Globaler Status","UNKNOWN":"Unbekannt","LAST_VERIFICATION":"Letzte Überprüfung","NEVER":"Niemals","NO_AML":"Keine Compliance-Überprüfung durchgeführt.","START_EVALUATION":"Bewertung starten →","BILLING":"Abrechnung","DRAFT":"Entwurf","DETAILS":"Details","NO_INVOICES":"Keine Rechnungen ausgestellt.","INVOICE_STATUS_PAID":"Bezahlt","INVOICE_STATUS_DRAFT":"Entwurf","INVOICE_STATUS_SENT":"Gesendet","INVOICE_STATUS_OVERDUE":"Überfällig","INVOICE_STATUS_PARTIAL":"Teilweise"
    }
  },
  it: {
    CLIENT_FORM: {
      "TITLE_EDIT":"Modifica","TITLE_NEW":"Nuovo","TITLE_CLIENT":"Cliente","TITLE_PHYSICAL":"Persona Fisica","SUBTITLE_PHYSICAL":"Identificazione & Conformità Individuale","TITLE_MORAL":"Società","SUBTITLE_MORAL":"Identificazione Aziendale & KYC","TITLE_ASSOCIATION":"Associazione","SUBTITLE_ASSOCIATION":"Identificazione Organizzazione No-Profit","TITLE_INSTITUTION":"Istituzione","SUBTITLE_INSTITUTION":"Identificazione Organizzazione Istituzionale","ASSOC_NAME":"Nome Associazione","INST_NAME":"Denominazione Istituzione","FISCAL_ID_APP":"Codice Fiscale (se applicabile)","CREATE_ASSOC":"Crea Associazione","CREATE_INST":"Crea Istituzione","CONTACT_HQ":"Contatto & Sede","SUBTITLE":"Tipi di Entità & Gestione KYC","ENTITY_TYPE":"Tipo di Entità","CONTACT_INFO":"Informazioni di Contatto","EMAIL":"Email Principale","EMAIL_INVALID":"Indirizzo email non valido","EMAIL_REQUIRED":"L'email è obbligatoria","PHONE":"Telefono","PHONE_REQUIRED":"Il telefono è obbligatorio","ADDRESS":"Indirizzo","COUNTRY":"Paese","COUNTRY_REQUIRED":"Il paese è obbligatorio","SECTOR":"Settore di Attività","SECTOR_SELECT":"Seleziona un settore","SECTOR_REQUIRED":"Il settore di attività è obbligatorio","IDENTITY_DETAILS":"Dettagli Identità","FIRST_NAME":"Nome","FIRST_NAME_REQUIRED":"Il nome è obbligatorio","LAST_NAME":"Cognome","LAST_NAME_REQUIRED":"Il cognome è obbligatorio","NATIONALITY":"Nazionalità","PASSPORT":"Carta d'Identità / Passaporto","BIRTH_DATE":"Data di Nascita","COMPANY_INFO":"Informazioni Azienda","COMMERCIAL_NAME":"Nome Commerciale","COMMERCIAL_NAME_REQUIRED":"Il nome commerciale è obbligatorio","LEGAL_FORM":"Forma Giuridica","RC":"N. Registro Imprese","RC_REQUIRED":"Il N. Registro Imprese è obbligatorio","FISCAL_ID":"N. Identificazione Fiscale","ORG_DETAILS":"Dettagli Organizzazione","ORG_NAME":"Nome Organizzazione","ORG_NAME_REQUIRED":"Il nome dell'organizzazione è obbligatorio","NATIONAL_REG":"N. Registro Nazionale","NATIONAL_REG_REQUIRED":"Il N. Registro Nazionale è obbligatorio","LEGAL_REP":"Rappresentante Legale","REP_LAST_NAME":"Cognome Rappresentante","REP_FIRST_NAME":"Nome Rappresentante","UBO_TITLE":"Titolari Effettivi (UBO)","ADD":"Aggiungi","UBO_FULL_NAME":"Nome Completo","UBO_OWNERSHIP":"Proprietà (%)","UBO_ROLE":"Ruolo","CONTACT_POINTS":"Punti di Contatto","OCCUPATION":"Occupazione","KYC_DOCS":"Documenti KYC","ADD_DOC":"Aggiungi un documento","CANCEL":"Annulla","SAVE_CHANGES":"Salva modifiche","CREATE_CLIENT":"Crea Cliente"
    },
    CLIENT_DETAILS: {
      "NO_ID":"Nessun ID cliente fornito.","LOAD_ERROR":"Impossibile caricare le informazioni del cliente.","LOAD_ERROR_GENERIC":"Si è verificato un errore durante il caricamento dei dati.","INDIVIDUAL":"Persona Fisica","COMPANY":"Società","NOT_PROVIDED":"Non fornito","COMPLIANCE_SHEET":"Scheda Conformità","CREATE_DOSSIER":"Crea una Pratica","ACTIVE_DOSSIERS":"Pratiche Attive","REFERENCE":"Riferimento","TITLE":"Titolo","OPEN_DATE":"Data Apertura","ACTION":"Azione","UNTITLED":"Senza Titolo","VIEW":"Visualizza","NO_DOSSIERS":"Nessuna pratica trovata per questo cliente.","AML_STATUS":"Stato AML/CFT","GLOBAL_STATUS":"Stato Globale","UNKNOWN":"Sconosciuto","LAST_VERIFICATION":"Ultima verifica","NEVER":"Mai","NO_AML":"Nessuna verifica di conformità eseguita.","START_EVALUATION":"Inizia valutazione →","BILLING":"Fatturazione","DRAFT":"Bozza","DETAILS":"Dettagli","NO_INVOICES":"Nessuna fattura emessa.","INVOICE_STATUS_PAID":"Pagata","INVOICE_STATUS_DRAFT":"Bozza","INVOICE_STATUS_SENT":"Inviata","INVOICE_STATUS_OVERDUE":"In Ritardo","INVOICE_STATUS_PARTIAL":"Parziale"
    }
  },
  ar: {
    CLIENT_FORM: {
      "TITLE_EDIT":"تعديل","TITLE_NEW":"جديد","TITLE_CLIENT":"عميل","TITLE_PHYSICAL":"شخص طبيعي","SUBTITLE_PHYSICAL":"التعريف والامتثال الفردي","TITLE_MORAL":"شركة","SUBTITLE_MORAL":"التعريف بالشركات و KYC","TITLE_ASSOCIATION":"جمعية","SUBTITLE_ASSOCIATION":"التعريف بالمنظمة غير الربحية","TITLE_INSTITUTION":"مؤسسة","SUBTITLE_INSTITUTION":"التعريف بالمنظمة المؤسسية","ASSOC_NAME":"اسم الجمعية","INST_NAME":"تعيين المؤسسة","FISCAL_ID_APP":"الرقم الضريبي (إن وجد)","CREATE_ASSOC":"إنشاء جمعية","CREATE_INST":"إنشاء مؤسسة","CONTACT_HQ":"الاتصال والمقر","SUBTITLE":"أنواع الكيانات وإدارة KYC","ENTITY_TYPE":"نوع الكيان","CONTACT_INFO":"معلومات الاتصال","EMAIL":"البريد الإلكتروني الرئيسي","EMAIL_INVALID":"عنوان بريد إلكتروني غير صالح","EMAIL_REQUIRED":"البريد الإلكتروني مطلوب","PHONE":"الهاتف","PHONE_REQUIRED":"الهاتف مطلوب","ADDRESS":"العنوان","COUNTRY":"البلد","COUNTRY_REQUIRED":"البلد مطلوب","SECTOR":"قطاع النشاط","SECTOR_SELECT":"حدد قطاعاً","SECTOR_REQUIRED":"قطاع النشاط مطلوب","IDENTITY_DETAILS":"تفاصيل الهوية","FIRST_NAME":"الاسم الشخصي","FIRST_NAME_REQUIRED":"الاسم الشخصي مطلوب","LAST_NAME":"الاسم العائلي","LAST_NAME_REQUIRED":"الاسم العائلي مطلوب","NATIONALITY":"الجنسية","PASSPORT":"الهوية / جواز السفر","BIRTH_DATE":"تاريخ الميلاد","COMPANY_INFO":"معلومات الشركة","COMMERCIAL_NAME":"الاسم التجاري","COMMERCIAL_NAME_REQUIRED":"الاسم التجاري مطلوب","LEGAL_FORM":"الشكل القانوني","RC":"رقم السجل التجاري","RC_REQUIRED":"رقم السجل التجاري مطلوب","FISCAL_ID":"الرقم الضريبي","ORG_DETAILS":"تفاصيل المنظمة","ORG_NAME":"اسم المنظمة","ORG_NAME_REQUIRED":"اسم المنظمة مطلوب","NATIONAL_REG":"رقم السجل الوطني","NATIONAL_REG_REQUIRED":"رقم السجل الوطني مطلوب","LEGAL_REP":"الممثل القانوني","REP_LAST_NAME":"الاسم العائلي للممثل","REP_FIRST_NAME":"الاسم الشخصي للممثل","UBO_TITLE":"المستفيدون الفعليون (UBO)","ADD":"إضافة","UBO_FULL_NAME":"الاسم الكامل","UBO_OWNERSHIP":"الملكية (%)","UBO_ROLE":"الدور","CONTACT_POINTS":"نقاط الاتصال","OCCUPATION":"المهنة","KYC_DOCS":"وثائق KYC","ADD_DOC":"إضافة وثيقة","CANCEL":"إلغاء","SAVE_CHANGES":"حفظ التغييرات","CREATE_CLIENT":"إنشاء عميل"
    },
    CLIENT_DETAILS: {
      "NO_ID":"لم يتم تقديم معرف العميل.","LOAD_ERROR":"تعذر تحميل معلومات العميل.","LOAD_ERROR_GENERIC":"حدث خطأ أثناء تحميل البيانات.","INDIVIDUAL":"شخص طبيعي","COMPANY":"شركة","NOT_PROVIDED":"غير متوفر","COMPLIANCE_SHEET":"ورقة الامتثال","CREATE_DOSSIER":"إنشاء قضية","ACTIVE_DOSSIERS":"القضايا النشطة","REFERENCE":"مرجع","TITLE":"عنوان","OPEN_DATE":"تاريخ الافتتاح","ACTION":"إجراء","UNTITLED":"بدون عنوان","VIEW":"عرض","NO_DOSSIERS":"لم يتم العثور على قضايا لهذا العميل.","AML_STATUS":"حالة مكافحة غسل الأموال","GLOBAL_STATUS":"الحالة العامة","UNKNOWN":"غير معروف","LAST_VERIFICATION":"آخر تحقق","NEVER":"أبداً","NO_AML":"لم يتم إجراء أي تحقق من الامتثال.","START_EVALUATION":"بدء التقييم ←","BILLING":"الفواتير","DRAFT":"مسودة","DETAILS":"تفاصيل","NO_INVOICES":"لم يتم إصدار أي فواتير.","INVOICE_STATUS_PAID":"مدفوعة","INVOICE_STATUS_DRAFT":"مسودة","INVOICE_STATUS_SENT":"مرسلة","INVOICE_STATUS_OVERDUE":"متأخرة","INVOICE_STATUS_PARTIAL":"جزئي"
    }
  }
};

const basePath = 'd:/avo-maitrise/front/public/assets/i18n';

for (const [lang, translations] of Object.entries(TRANSLATIONS)) {
  const filePath = `${basePath}/${lang}.json`;
  if (fs.existsSync(filePath)) {
    const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));
    data['CLIENT_FORM'] = translations.CLIENT_FORM;
    data['CLIENT_DETAILS'] = translations.CLIENT_DETAILS;
    fs.writeFileSync(filePath, JSON.stringify(data, null, 2));
    console.log(`Updated ${lang}.json for CLIENT_FORM and CLIENT_DETAILS`);
  }
}
